name: user-timeline-tools
dependencies:
- anaconda-client=1.2.2=py27_0
- clyent=1.2.1=py27_0
- openssl=1.0.2g=0
- pip=8.0.3=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- readline=6.2=2
- requests=2.9.1=py27_0
- setuptools=20.1.1=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - twitter==1.17.1

